import { Controller } from "react-hook-form";

export const arLabels = {
    title: "başlık",
    sub_title: 'alt yazı',
    description: 'Tanım',
    main_image: 'Ana resim',
    size: 'boyut',
      bath_count: 'banyo sayısı ',
      bed_room_count: 'yatak odası sayısı',
      floor_type: 'zemin tipi',
      is_floor_available: 'kat mevcut mu',
      additional_space_type:'ek alan türü',
      is_additional_space:'ek alan',
      furnished_type: 'mobilyalı tip ',
      is_furnished:'döşenmiştir',
      revolution_date:'devrim tarihi ',
      ceiling_height: ' tavan yüksekliği',
      is_ceiling: 'tavan',
      construction_year: ' Inşaat yılı ',
      first_floor_map_image: 'birinci kat harita resmi',
      second_floor_map_image: 'ikinci kat harita resmi',
      address: 'adres',
      rating_count: 'derecelendirme sayısı ',
      currency: 'para birimi',
      price: 'fiyat',
      has_heating: 'ısıtma var ',
      heating_type: 'ısıtma tipi',
      has_window: ' penceresi var',
      window_type: 'pencere tipi',
      has_air_conditioners: 'klimalar var ',
      has_cable_tv: 'kablolu televizyon var',
      has_fire_place: 'gazlı şömine var',
      has_intercorm: 'interkorm var',
      has_wifi: ' Wi-Fi var ',
      has_ventillation: 'havalandırma var',
      has_garage: ' garajı var',
      has_swimming_pool: ' yüzme havuzu var ',
      has_parking: 'park yeri var ',
      has_garden: ' bahçesi var',
      school_distance: 'okul mesafesi ',
      university_distance: ' üniversite mesafesi',
      hospital_distance: 'hastane mesafesi ',
      metro_station_distance: ' metro istasyonu mesafesi ',
      grocery_center_distance: '  bakkal merkez mesafesi',
      market_distance: 'pazar mesafesi ',
      gym_distance: '  spor salonu mesafesi',
      river_distance: 'nehir mesafesi ',
      contact_no: 'İletişim Numarası ',
      disabled_access_type: 'engelli erişim türü',
      fence_type: 'çit tipi ',
      security_camaras_count: ' güvenlik kameraları sayımı ',
      is_pet_friendly: 'evcil hayvan dostudur  ',
      wellness_distance: ' sağlıklı yaşam mesafesi',
    
};